### ISSUE TITLE
Mac上安装node.js

### ISSUE THREAD

**Issue by Charles1208** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#13]

**Comment by Charles1208** [comment]
请问为什么装完node.js后，在终端上命令提示不行。。。

**Comment by naffan2014** [comment]
如果用mac，强烈建议先安装[homebrew](http://brew.sh)，用brew安装node.js。
方法如下：
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
等待完成后，执行
brew install node即可。
node也需要npm，brew install npm即可。
