### ISSUE TITLE
翻譯探討

### ISSUE THREAD

**Issue by huihsinhsiao** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#131]
你好，非常感謝這個資源，閱讀繁體中文版時發現有更好的敘述：

`原文` I'm trying to replace the color table on an image with values of my choosing.
`現譯` 我正試著用替換一幅圖片的色碼成自己選定的色碼
`我的建議`  我正試著把一幅圖片的色碼替換成自己選定的色碼

**Comment by ryanhanwu** [comment]
good suggestion, please submit a PR!
