### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by PoorRita** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#133]
Is this original?

**Comment by xiaopangju** [comment]
no
please see link in readme

Yours faithfully,

Haoran Du


________________________________
From: JunYe ***@***.***>
Sent: Thursday, July 29, 2021 4:52:48 PM
To: ryanhanwu/How-To-Ask-Questions-The-Smart-Way ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ryanhanwu/How-To-Ask-Questions-The-Smart-Way] hello (#133)


Is this original?

**Comment by zhaofx** [comment]
---Original---
From: "Haoran ***@***.*** ithub.com&gt;
Date: Fri, Jul 30, 2021 13:27 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [ryanhanwu/How-To-Ask-Questions-The-Smart-Way] hello (#133)




 no
 please see link in readme
 
 Yours faithfully,
 
 Haoran Du
 
 
 ________________________________
 From: JunYe ***@***.***&gt;
 Sent: Thursday, July 29, 2021 4:52:48 PM
 To: ryanhanwu/How-To-Ask-Questions-The-Smart-Way ***@***.***&gt;
 Cc: Subscribed ***@***.***&gt;
 Subject: [ryanhanwu/How-To-Ask-Questions-The-Smart-Way] hello (#133)
 
 
 Is this original?
