### ISSUE TITLE
How to Implement lazy Iterator based on these binary tree code

### ISSUE THREAD

**Issue by MICROSOFT55555555hh** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#134]
package Algorthims;

import java.util.ArrayList;

import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;

public class Trees {

	public static void main(String[] args) {
		LinkedBinaryTree<Integer> BT=new LinkedBinaryTree<Integer>();
		Position<Integer> bt1=BT.addRoot(30);
		Position<Integer> bt2=BT.addLeft(bt1, 50);
		Position<Integer> bt3=BT.addRight(bt1, 60);
		for(Position<Integer> p:BT.positions()) {
			System.out.println(p.getElement());
		}
		printPreorderIndent(BT,BT.root(),0);
		printPreorderLabeled(BT,BT.root(),new ArrayList<Integer>());
	}
	
	public interface Position<E>{
		E getElement();
	}
	
	public interface Tree<E> extends Iterable<E>{
		Position<E> root();
		Position<E> parent(Position<E> p) throws IllegalArgumentException;
		Iterable<Position<E>> children(Position<E> p) throws IllegalArgumentException;
		int numChildren(Position<E> p) throws IllegalArgumentException;
		boolean isInternal(Position<E> p) throws IllegalArgumentException;
		boolean isExternal(Position<E> p) throws IllegalArgumentException;
		boolean isRoot(Position<E> p) throws IllegalArgumentException;
		int size();
		boolean isEmpty();
		Iterator<E> iterator();
		Iterable<Position<E>> positions();
	}
	
	public static abstract class AbstractTree<E> implements Tree<E>{
		public boolean isInternal(Position<E> p) {return numChildren(p)>0;}
		public boolean isExternal(Position<E> p) {return numChildren(p)==0;}
		public boolean isRoot(Position<E> p) {return p==root();}
		public boolean isEmpty() {return size()==0;} 
		public int depth(Position<E> p) {
			if(isRoot(p))
				return 0;
			else
				return 1+depth(parent(p));
		}
		
		
		public int height(Position<E> p) {
			int h=0;
			for(Position<E> c:children(p)) {
				h=Math.max(h, 1+height(c));
			}
			return h;
		}
		
		
	}
	
	public interface BinaryTree<E> extends Tree<E>{
		
		Position<E> left(Position<E> p) throws IllegalStateException;
		Position<E> right(Position<E> p) throws IllegalStateException;
		Position<E> sibling(Position<E> p) throws IllegalStateException;
		
	}
	
	public static abstract class AbstractBinaryTree<E> extends AbstractTree<E> implements BinaryTree<E>{
		public Position<E> sibling(Position<E> p){
			Position<E> parent=parent(p);
			if(parent==null) return null;
			if(p==left(parent)) return right(parent);
			else return left(parent);
			
		}
		
		public int numChildren(Position<E> p) {
			int count=0;
			if(left(p)!=null)
				count++;
			if(right(p)!=null)
				count++;
			return count;
		}
		
		public Iterable<Position<E>> children(Position<E> p) {
			List<Position<E>> snapshot=new ArrayList<>(2);
			if(left(p)!=null)
				snapshot.add(left(p));
			if(right(p)!=null)
					snapshot.add(right(p));
			return snapshot;
			
		}
		
	}
	
       //A Node has element parent,left,right .
	public static class LinkedBinaryTree<E> extends AbstractBinaryTree<E>{
		
		protected static class Node<E> implements Position<E>{
			
			private E element;
			private Node<E> parent;
			private Node<E> left;
			private Node<E> right;
			
			public Node(E e,Node<E> above,Node<E> leftChild,Node<E> rightChild) {
				element=e;
				parent=above;
				left=leftChild;
				right=rightChild;
			}
			
			@Override
			public E getElement() {
				
				return element;
			}
			
			public Node<E> getParent(){return parent;}
			public Node<E> getLeft(){return left;}
			public Node<E> getRight(){return right;}
			
			public void setElement(E e) {element=e;}
			public void setParent(Node<E> above) {parent=above;}
			public void setLeft(Node<E> leftChild) {left=leftChild;}
			public void setRight(Node<E> rightChild) {right=rightChild;}
		}
		
		protected Node<E> createNode(E e,Node<E> parent,Node<E> left,Node<E> right){
			return new Node<E>(e,parent,left,right);
		}
		
		protected Node<E> root=null;
		private int size=0;
		
		public LinkedBinaryTree() {}
		
		protected Node<E> validate(Position<E> p) throws IllegalStateException{
			if(!(p instanceof Node)) throw new IllegalStateException("Not Valid position type");
			Node<E> node=(Node<E>)p;
			if(node.getParent()==node) {
				throw new IllegalStateException("P is no longer in the tree");
			}
			return node;
		}
		
		
		
		@Override
		public Position<E> left(Position<E> p) throws IllegalStateException {
			Node<E> node=validate(p);
			return node.getLeft();
		}

		@Override
		public Position<E> right(Position<E> p) throws IllegalStateException {
			Node<E> node=validate(p);
			return node.getRight();
		}

		@Override
		public Position<E> root() {
			
			return root;
		}

		@Override
		public Position<E> parent(Position<E> p) throws IllegalArgumentException {
			Node<E> node=validate(p);
			return node.getParent();
		}

		@Override
		public int size() {
			
			return size;
		}
		
		public Position<E> addRoot(E e) throws IllegalStateException{
			if(!isEmpty()) throw new IllegalStateException("Tree is not Empty");
			root=createNode(e,null,null,null);
			size=1;
			return root;
		}
		
		public Position<E> addLeft(Position<E> p,E e) throws IllegalStateException{
			Node<E> parent=validate(p);
			if(parent.getLeft()!=null) throw new IllegalStateException(" p has left child");
			Node<E> child=createNode(e,parent,null,null);
			parent.setLeft(child);
			size++;
			return child;
		}
		
		public Position<E> addRight(Position<E> p,E e) throws IllegalStateException{
			Node<E> parent=validate(p);
			if(parent.getRight()!=null) throw new IllegalStateException(" p has right child");
			Node<E> child=createNode(e,parent,null,null);
			parent.setRight(child);
			size++;
			return child;
		}
		
		public E set(Position<E> p,E e) throws IllegalStateException{
			Node<E> node=validate(p);
			E temp=node.getElement();
			node.setElement(e);
			return temp;	
		}
		
		public void attach(Position<E> p,LinkedBinaryTree<E> t1,LinkedBinaryTree<E> t2) 
				throws IllegalArgumentException{
			Node<E> node=validate(p);
			if(isInternal(p)) throw new IllegalArgumentException("p must be in a leaf");
			size+=t1.size()+t2.size();
			
			if(!t1.isEmpty()) {
				t1.root.setParent(node);
				node.setLeft(t1.root);
				t1.root=null;
				t1.size=0;
			}
			if(!t2.isEmpty()) {
				t2.root.setParent(node);
				node.setRight(t2.root);
				t2.root=null;
				t2.size=0;
			}
		}
		
		public E remove(Position<E> p) throws IllegalArgumentException{
			Node<E> node=validate(p);
			if(numChildren(p)==2) throw new IllegalArgumentException("p has two children");
			Node<E> child=(node.getLeft()!=null?node.getLeft():node.getRight());//child maybe null
			if(child!=null)
				child.setParent(node.getParent());
			if(node==root)
				root=child;
			else {
				Node<E> parent=node.getParent();
				if(node==parent.getLeft())
					parent.setLeft(child);
				else
					parent.setRight(child);
			}
			size--;
			E temp=node.getElement();
			node.setElement(null);
			node.setLeft(null);
			node.setParent(node);
			node.setRight(null);
			return temp;
		}
		
               //Below are implemented based on snapshot iteration. 

		private class ElementIterator implements Iterator<E>{
			Iterator<Position<E>> posIterator= positions().iterator();
			@Override
			public boolean hasNext() {
				
				return posIterator.hasNext();
			}

			@Override
			public E next() {
				
				return posIterator.next().getElement();
			}
			
			public void remove() {
				posIterator.remove();
			}
		}
		
		
		@Override
		public Iterator<E> iterator() {
			
			return new ElementIterator();
		}

		@Override
		public Iterable<Position<E>> positions() {
			
			return preorder();
		}
		
		private void preorderSubtree(Position<E> p,List<Position<E>> snapshot) {
			snapshot.add(p);
			for(Position<E> c:children(p)) {
				preorderSubtree(c,snapshot);
			}
		}
		
		public Iterable<Position<E>> preorder(){
			List<Position<E>> snapshot=new ArrayList<>();
			if(!isEmpty())
				preorderSubtree(root(),snapshot);
			return snapshot;
		}
		
		private void postorderSubtree(Position<E> p,List<Position<E>> snapshot) {
			for(Position<E> c:children(p)) {
				postorderSubtree(c,snapshot);
			}
			snapshot.add(p);
		}
		
		public Iterable<Position<E>> postorder(){
			List<Position<E>> snapshot=new ArrayList<>();
			if(!isEmpty())
				postorderSubtree(root(),snapshot);
			return snapshot;
		}
		
		public Iterable<Position<E>> breathfirst(){
			List<Position<E>> snapshot=new ArrayList<>();
			if(!isEmpty()) {
				Queue<Position<E>> fringe=new LinkedList<>();
				fringe.add(root());
				while(!fringe.isEmpty()) {
					Position<E> p=fringe.poll();
					snapshot.add(p);
					for(Position<E> c:children(p)) {
						fringe.add(c);
					}
					
				}
				
			}
			return snapshot;	
		}
		
		private void inorderSubtree(Position<E> p,List<Position<E>> snapshot) {
			if(left(p)!=null)
				inorderSubtree(left(p),snapshot);
			snapshot.add(p);
			if(right(p)!=null)
				inorderSubtree(right(p),snapshot);
			
		}
		
		public Iterable<Position<E>> inorder(){
			List<Position<E>> snapshot=new ArrayList();
			if(!isEmpty()) {
				inorderSubtree(root(),snapshot);
			}
			return snapshot;
			
		}
	}
	
}

//Method of preorder,postorder, inorder are implemented based on snapshot iteration.

**Comment by xiaopangju** [comment]
do not ask questions here

Yours faithfully,

Haoran Du


________________________________
From: MICROSOFT55555555hh ***@***.***>
Sent: Saturday, July 31, 2021 4:15:43 AM
To: ryanhanwu/How-To-Ask-Questions-The-Smart-Way ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ryanhanwu/How-To-Ask-Questions-The-Smart-Way] How to Implement lazy Iterator based on these binary tree code (#134)


package Algorthims;

import java.util.ArrayList;

import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;

public class Trees {

public static void main(String[] args) {
        LinkedBinaryTree<Integer> BT=new LinkedBinaryTree<Integer>();
        Position<Integer> bt1=BT.addRoot(30);
        Position<Integer> bt2=BT.addLeft(bt1, 50);
        Position<Integer> bt3=BT.addRight(bt1, 60);
        for(Position<Integer> p:BT.positions()) {
                System.out.println(p.getElement());
        }
        printPreorderIndent(BT,BT.root(),0);
        printPreorderLabeled(BT,BT.root(),new ArrayList<Integer>());
}

public interface Position<E>{
        E getElement();
}

public interface Tree<E> extends Iterable<E>{
        Position<E> root();
        Position<E> parent(Position<E> p) throws IllegalArgumentException;
        Iterable<Position<E>> children(Position<E> p) throws IllegalArgumentException;
        int numChildren(Position<E> p) throws IllegalArgumentException;
        boolean isInternal(Position<E> p) throws IllegalArgumentException;
        boolean isExternal(Position<E> p) throws IllegalArgumentException;
        boolean isRoot(Position<E> p) throws IllegalArgumentException;
        int size();
        boolean isEmpty();
        Iterator<E> iterator();
        Iterable<Position<E>> positions();
}

public static abstract class AbstractTree<E> implements Tree<E>{
        public boolean isInternal(Position<E> p) {return numChildren(p)>0;}
        public boolean isExternal(Position<E> p) {return numChildren(p)==0;}
        public boolean isRoot(Position<E> p) {return p==root();}
        public boolean isEmpty() {return size()==0;}
        public int depth(Position<E> p) {
                if(isRoot(p))
                        return 0;
                else
                        return 1+depth(parent(p));
        }


        public int height(Position<E> p) {
                int h=0;
                for(Position<E> c:children(p)) {
                        h=Math.max(h, 1+height(c));
                }
                return h;
        }


}

public interface BinaryTree<E> extends Tree<E>{

        Position<E> left(Position<E> p) throws IllegalStateException;
        Position<E> right(Position<E> p) throws IllegalStateException;
        Position<E> sibling(Position<E> p) throws IllegalStateException;

}

public static abstract class AbstractBinaryTree<E> extends AbstractTree<E> implements BinaryTree<E>{
        public Position<E> sibling(Position<E> p){
                Position<E> parent=parent(p);
                if(parent==null) return null;
                if(p==left(parent)) return right(parent);
                else return left(parent);

        }

        public int numChildren(Position<E> p) {
                int count=0;
                if(left(p)!=null)
                        count++;
                if(right(p)!=null)
                        count++;
                return count;
        }

        public Iterable<Position<E>> children(Position<E> p) {
                List<Position<E>> snapshot=new ArrayList<>(2);
                if(left(p)!=null)
                        snapshot.add(left(p));
                if(right(p)!=null)
                                snapshot.add(right(p));
                return snapshot;

        }

}

   //A Node has element parent,left,right .
public static class LinkedBinaryTree<E> extends AbstractBinaryTree<E>{

        protected static class Node<E> implements Position<E>{

                private E element;
                private Node<E> parent;
                private Node<E> left;
                private Node<E> right;

                public Node(E e,Node<E> above,Node<E> leftChild,Node<E> rightChild) {
                        element=e;
                        parent=above;
                        left=leftChild;
                        right=rightChild;
                }

                @Override
                public E getElement() {

                        return element;
                }

                public Node<E> getParent(){return parent;}
                public Node<E> getLeft(){return left;}
                public Node<E> getRight(){return right;}

                public void setElement(E e) {element=e;}
                public void setParent(Node<E> above) {parent=above;}
                public void setLeft(Node<E> leftChild) {left=leftChild;}
                public void setRight(Node<E> rightChild) {right=rightChild;}
        }

        protected Node<E> createNode(E e,Node<E> parent,Node<E> left,Node<E> right){
                return new Node<E>(e,parent,left,right);
        }

        protected Node<E> root=null;
        private int size=0;

        public LinkedBinaryTree() {}

        protected Node<E> validate(Position<E> p) throws IllegalStateException{
                if(!(p instanceof Node)) throw new IllegalStateException("Not Valid position type");
                Node<E> node=(Node<E>)p;
                if(node.getParent()==node) {
                        throw new IllegalStateException("P is no longer in the tree");
                }
                return node;
        }



        @Override
        public Position<E> left(Position<E> p) throws IllegalStateException {
                Node<E> node=validate(p);
                return node.getLeft();
        }

        @Override
        public Position<E> right(Position<E> p) throws IllegalStateException {
                Node<E> node=validate(p);
                return node.getRight();
        }

        @Override
        public Position<E> root() {

                return root;
        }

        @Override
        public Position<E> parent(Position<E> p) throws IllegalArgumentException {
                Node<E> node=validate(p);
                return node.getParent();
        }

        @Override
        public int size() {

                return size;
        }

        public Position<E> addRoot(E e) throws IllegalStateException{
                if(!isEmpty()) throw new IllegalStateException("Tree is not Empty");
                root=createNode(e,null,null,null);
                size=1;
                return root;
        }

        public Position<E> addLeft(Position<E> p,E e) throws IllegalStateException{
                Node<E> parent=validate(p);
                if(parent.getLeft()!=null) throw new IllegalStateException(" p has left child");
                Node<E> child=createNode(e,parent,null,null);
                parent.setLeft(child);
                size++;
                return child;
        }

        public Position<E> addRight(Position<E> p,E e) throws IllegalStateException{
                Node<E> parent=validate(p);
                if(parent.getRight()!=null) throw new IllegalStateException(" p has right child");
                Node<E> child=createNode(e,parent,null,null);
                parent.setRight(child);
                size++;
                return child;
        }

        public E set(Position<E> p,E e) throws IllegalStateException{
                Node<E> node=validate(p);
                E temp=node.getElement();
                node.setElement(e);
                return temp;
        }

        public void attach(Position<E> p,LinkedBinaryTree<E> t1,LinkedBinaryTree<E> t2)
                        throws IllegalArgumentException{
                Node<E> node=validate(p);
                if(isInternal(p)) throw new IllegalArgumentException("p must be in a leaf");
                size+=t1.size()+t2.size();

                if(!t1.isEmpty()) {
                        t1.root.setParent(node);
                        node.setLeft(t1.root);
                        t1.root=null;
                        t1.size=0;
                }
                if(!t2.isEmpty()) {
                        t2.root.setParent(node);
                        node.setRight(t2.root);
                        t2.root=null;
                        t2.size=0;
                }
        }

        public E remove(Position<E> p) throws IllegalArgumentException{
                Node<E> node=validate(p);
                if(numChildren(p)==2) throw new IllegalArgumentException("p has two children");
                Node<E> child=(node.getLeft()!=null?node.getLeft():node.getRight());//child maybe null
                if(child!=null)
                        child.setParent(node.getParent());
                if(node==root)
                        root=child;
                else {
                        Node<E> parent=node.getParent();
                        if(node==parent.getLeft())
                                parent.setLeft(child);
                        else
                                parent.setRight(child);
                }
                size--;
                E temp=node.getElement();
                node.setElement(null);
                node.setLeft(null);
                node.setParent(node);
                node.setRight(null);
                return temp;
        }

           //Below are implemented based on snapshot iteration.

        private class ElementIterator implements Iterator<E>{
                Iterator<Position<E>> posIterator= positions().iterator();
                @Override
                public boolean hasNext() {

                        return posIterator.hasNext();
                }

                @Override
                public E next() {

                        return posIterator.next().getElement();
                }

                public void remove() {
                        posIterator.remove();
                }
        }


        @Override
        public Iterator<E> iterator() {

                return new ElementIterator();
        }

        @Override
        public Iterable<Position<E>> positions() {

                return preorder();
        }

        private void preorderSubtree(Position<E> p,List<Position<E>> snapshot) {
                snapshot.add(p);
                for(Position<E> c:children(p)) {
                        preorderSubtree(c,snapshot);
                }
        }

        public Iterable<Position<E>> preorder(){
                List<Position<E>> snapshot=new ArrayList<>();
                if(!isEmpty())
                        preorderSubtree(root(),snapshot);
                return snapshot;
        }

        private void postorderSubtree(Position<E> p,List<Position<E>> snapshot) {
                for(Position<E> c:children(p)) {
                        postorderSubtree(c,snapshot);
                }
                snapshot.add(p);
        }

        public Iterable<Position<E>> postorder(){
                List<Position<E>> snapshot=new ArrayList<>();
                if(!isEmpty())
                        postorderSubtree(root(),snapshot);
                return snapshot;
        }

        public Iterable<Position<E>> breathfirst(){
                List<Position<E>> snapshot=new ArrayList<>();
                if(!isEmpty()) {
                        Queue<Position<E>> fringe=new LinkedList<>();
                        fringe.add(root());
                        while(!fringe.isEmpty()) {
                                Position<E> p=fringe.poll();
                                snapshot.add(p);
                                for(Position<E> c:children(p)) {
                                        fringe.add(c);
                                }

                        }

                }
                return snapshot;
        }

        private void inorderSubtree(Position<E> p,List<Position<E>> snapshot) {
                if(left(p)!=null)
                        inorderSubtree(left(p),snapshot);
                snapshot.add(p);
                if(right(p)!=null)
                        inorderSubtree(right(p),snapshot);

        }

        public Iterable<Position<E>> inorder(){
                List<Position<E>> snapshot=new ArrayList();
                if(!isEmpty()) {
                        inorderSubtree(root(),snapshot);
                }
                return snapshot;

        }
}


}

//Method of preorder,postorder, inorder are implemented based on snapshot iteration.
