### ISSUE TITLE
文章可能有错字

### ISSUE THREAD

**Issue by MouseJW** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#15]
在 “如何处理答案>处理无礼的回应” 的第三段的开头的第一句话“另一方面，你偶而真的会碰到无礼和无聊的言行。”   ，那个“偶而” 是 “偶尔”吗？

![default](https://cloud.githubusercontent.com/assets/24412152/23941011/167c70fe-09a2-11e7-915f-2101ad87a421.png)

**Comment by Sunlcy** [comment]
@MouseJW 其实这并不是一个错别字，只是目前并不常用了，我们现在经常写作”偶尔“。
下面是英文原文：

> On the other hand, you will **occasionally** run across rudeness and posturing that is quite gratuitous.

很明显“occasionally”对应中文的“偶尔”或者“偶而”。

不过我觉得为了符合目前的表达习惯，我觉得应该改为”偶尔“。
