### ISSUE TITLE
oraclelogminerreader 写入MySQL   源表就一个字段name 目标表就一个字段name    不能写入  可以帮忙解决一下吗  

### ISSUE THREAD

**Issue by liquan00759** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#158]
{
  "job": {
    "content": [
      {
        "nameMapping": {
          "schemaMappings": {
            "liquan": "liquan"
          },
          "tableMappings": {
            "liquan": {
               "test": "test"
            }
          },
          "fiedMappings": {
            "liquan": {
              "test": {
                "name": "name"
              }
            }
          }
        },
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.109.136:1521:orcl",
            "username": "liquan",
            "password": "123456",
            "supportAutoAddLog": false,
            "table": ["liquan.test"],
            "cat": "UPDATE,INSERT,DELETE",
            "pavingData" : "true",
            "readPosition" : "CURRENT",
            "queryTimeout": 1800
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "root",
            "password": "123.com",
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://192.168.109.128:3306/liquan?useSSL=false",
                "table": [
                  "test"
                ]
              }
            ],
            "writeMode": "insert",
            "column": [
             {
              "name": "name",
              "type": "char"

              }
            ]
          }
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      },
      "speed": {
        "readerChannel": 1,
        "writerChannel": 1
      }
    }
  }
}

**Comment by Geno1024** [comment]
您知道这个仓库是用来干什么的吗，先仔细看看仓库的内容吧

**Comment by liquan00759** [comment]
我需求使用oracle  logminer  实时同步到mysql   不可以这样用吗

**Comment by xiaopangju** [comment]
`许多项目在他们的使用协助/说明网页中链接了本指南，这么做很好，我们也鼓励大家都这么做。但如果你是负责管理这个项目网页的人，请在超链接附近的显著位置上注明：

本指南不提供此项目的实际支持服务！

我们已经深刻领教到少了上述声明所带来的痛苦。因为少了这点声明，我们不停地被一些白痴纠缠。这些白痴认为既然我们发布了这本指南，那么我们就有责任解决世上所有的技术问题。

如果你因寻求某些帮助而阅读本指南，并在离开时还觉得可以从本文作者这里得到直接帮助，那你就是我们之前说的那些白痴之一。别问我们问题，我们只会忽略你。我们在这本指南中是教你如何从那些真正懂得你所遇到软件或硬件问题的人取得协助，而 99% 的情况下那不会是我们。除非你确定本指南的作者之一刚好是你所遇到的问题领域的专家，否则请不要打扰我们，这样大家都会开心一点。`
引用自https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%A3%B0%E6%98%8E

**Comment by Geno1024** [comment]
您真的什么都不看吗？

> 许多项目在他们的使用协助/说明网页中链接了本指南，这么做很好，我们也鼓励大家都这么做。但如果你是负责管理这个项目网页的人，请在超链接附近的显著位置上注明：
> 本指南不提供此项目的实际支持服务！
> 我们已经深刻领教到少了上述声明所带来的痛苦。因为少了这点声明，我们不停地被一些白痴纠缠。这些白痴认为既然我们发布了这本指南，那么我们就有责任解决世上所有的技术问题。
> 如果你因寻求某些帮助而阅读本指南，并在离开时还觉得可以从本文作者这里得到直接帮助，那你就是我们之前说的那些白痴之一。别问我们问题，我们只会忽略你。我们在这本指南中想教你如何从那些真正懂得你所遇到的软件或硬件问题的人处取得协助，而 99% 的情况下那不会是我们。除非你确定本指南的作者之一刚好是你所遇到的问题领域的专家，否则请不要打扰我们，这样大家都会开心一点。

**Comment by liquan00759** [comment]
[Geno1024](https://github.com/Geno1024)    你用过吗  可否指导下呢    我需要用oracle logminer 实时同步到mysql

**Comment by xiaopangju** [comment]
> 您真的什么都不看吗？
> 
> > 许多项目在他们的使用协助/说明网页中链接了本指南，这么做很好，我们也鼓励大家都这么做。但如果你是负责管理这个项目网页的人，请在超链接附近的显著位置上注明：
> > 本指南不提供此项目的实际支持服务！
> > 我们已经深刻领教到少了上述声明所带来的痛苦。因为少了这点声明，我们不停地被一些白痴纠缠。这些白痴认为既然我们发布了这本指南，那么我们就有责任解决世上所有的技术问题。
> > 如果你因寻求某些帮助而阅读本指南，并在离开时还觉得可以从本文作者这里得到直接帮助，#### **那你就是我们之前说的那些白痴之一**。别问我们问题，我们只会忽略你。我们在这本指南中想教你如何从那些真正懂得你所遇到的软件或硬件问题的人处取得协助，而 99% 的情况下那不会是我们。除非你确定本指南的作者之一刚好是你所遇到的问题领域的专家，否则请不要打扰我们，这样大家都会开心一点。

你回复错人了

**Comment by xiaopangju** [comment]
> [Geno1024](https://github.com/Geno1024) 你用过吗 可否指导下呢 我需要用oracle logminer 实时同步到mysql

你能认真看看我的回复吗

**Comment by liquan00759** [comment]
都想骂街 破chunjun 文档那么烂  不能使用   有本事给指导下   推广这个产品  难道 不解决用户的问题吗

**Comment by Geno1024** [comment]
@liquan00759 您好，如果您不需要使用眼睛的话，可以捐献给有需要的人，可以去 https://www.codac.org.cn/ 看看 :rofl:

**Comment by Geno1024** [comment]
> 

请问您有没有尝试过看看你现在在什么仓库下发言，看看这个仓库的内容是什么呢？

**Comment by liquan00759** [comment]
哈哈   不好意思  很少使用这个    刚明白过来   提错仓库了
