### ISSUE TITLE
c++問題

### ISSUE THREAD

**Issue by nerfygf** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#175]
輸入學生c期中考選擇題的答案，並與標準答案對照，計算答對和答錯的題數，試撰寫一程式執行之。scanf("%c",&ans[i]);
學生c期中考選擇題的答案:accbdc
          標準答案:adcbad
            計算答對:3
           答錯的題數:3

**Comment by Geno1024** [comment]
> - [ ] 我确认，我已经看过[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)，并且提出的 Issue 是关于《提问的智慧》的翻译本身，而非某个软件。
