### ISSUE TITLE
翻译探讨

### ISSUE THREAD

**Issue by creeper2556** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#179]
- [x] 我确认，我已经看过[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)，并且提出的 Issue 是关于《提问的智慧》的翻译本身，而非某个软件。

原文:`We call people like this “losers”`
翻译: `我们称这样的人为 失败者（撸瑟）`
建议改为:`我们称这样的人为 失败者（losers）`
理由:`losers`不应音译,应向`以便更高效地利用时间来回答赢家（winner）的问题。`一句一样将其保留英文

**Comment by liangyuanpeng** [comment]
这个我同意

**Comment by Gemini2035** [comment]
你干啥啊，主人不在，我陪您玩啊~

**Comment by YeatsLiao** [comment]
true

**Comment by Gemini2035** [comment]
你干啥啊，主人不在，我陪您玩啊~
