### ISSUE TITLE
可否與 GitBook 進行整合?

### ISSUE THREAD

**Issue by chusiang** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#2]
Hi, ryanhanwu:

進來有了 GitBook 這服務，它可以將使用 markdown 語法所寫成的文章整理成冊，相信這會更利於各個平台的使用者閱讀。

成果請參考在下所撰寫的[《完全用 GNU/Linux 工作》](http://chusiang.gitbooks.io/working-on-gnu-linux/)一書。

如果會造成您的負擔，那麼在下會先行 fork 並進行後續相關設置。

**Comment by ryanhanwu** [comment]
Very good suggestion, I will do it soon and let  you know if I have any question.

btw, this is **ryanhanwu**

**Comment by chusiang** [comment]
Thank you very much! :+1:
