### ISSUE TITLE
Could you please fix the list?

### ISSUE THREAD

**Issue by dqwyy** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#31]
![1.png](https://i.loli.net/2018/04/15/5ad2f2f39b08f.png)

![2.png](https://i.loli.net/2018/04/15/5ad2f2f3f219a.png)

As the screenshots show, the numbered lists aren't showed correctly. I checked the raw Markdown codes but didn't find the problem. Could you please fix it? Thanks.

Besides, I have another suggestion. Maybe you can use the CJK quotation marks (use `「」` in zh-tw and use `“”` in zh-cn) instead of using the English quotation marks `""`.

**Comment by ryanhanwu** [comment]
Thank you for reporting the issue
