### ISSUE TITLE
OPENWRT R8.1.7,EA8500的VLAN

### ISSUE THREAD

**Issue by jackyan999** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#42]
我的EA8500自R8.1固件后， 如果刷完固件复位就会丢失"启用VLAN"的选项，且这时候WAN显示的状态是不活动的。如果刷完固件不复位WAN和VLAN正常，但使用二，三天后就会莫明发生上述的情况而无法使用了，我试了几种方法，包括删除WAN和VLAN后再重建，情况依然是无法启用。不知道是什么原因造成的，请提供帮助，谢谢！

**Comment by ryanhanwu** [comment]
Irrelevant issue
