### ISSUE TITLE
一些翻译建议：Chapter “Send questions in accessible, standard formats”

### ISSUE THREAD

**Issue by DKJust** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#8]
>- 原文“Assume that your respondents will be reading mail on 80-character-wide text displays and set your line wrap accordingly, to something less than 80.”
>- 原翻译“设想你的读者是在80个字符宽的终端机上阅读邮件，最好设置你的断行点小于80字。”
>- 原文中的80应是指数字80。
>- 建议改成"最好设置你的断行点小于80。"或者"最好设置你的断行点小于80字符宽。"

>- 原文“However, do not wrap data (such as log file dumps or session transcripts) at any fixed column width.”
>- 原翻译“但是，也不要用任何固定断行资料（譬如日志档案拷贝或会话记录）。”
>- 原文的意思应该是不要改变固定断行资料本身的断行。
>- 建议改成"但是，也不要因此改变任何固定断行资料（譬如日志档案拷贝或会话记录）。"

**Comment by ryanhanwu** [comment]
These are very good suggestions, why don't you send me a PR? I'll merge it asap
